const users=[
    {
        id:1,
        name:'Hari',
        isActive:true,
        age:22,
    },
    {
        id:2,
        name:'Nikhli',
        isActive:false,
        age:22,
    },
    {
        id:3,
        name:'Sundar',
        isActive:true,
        age:30,
    },
    {
        id:4,
        name:'Damodar',
        isActive:false,
        age:33,
    },
    {
        id:5,
        name:'Chandan',
        isActive:true,
        age:30,
    },
    {
        id:6,
        name:'Bhushan',
        isActive:false,
        age:35,
    },
    {
        id:7,
        name:'Gagan',
        isActive:true,
        age:21,
    },
    {
        id:8,
        name:'Amit',
        isActive:false,
        age:29,
    },
    {
        id:9,
        name:'Sumit',
        isActive:false,
        age:25,
    },
    {
        id:10,
        name:'Satyajeet',
        isActive:true,
        age:38,
    },

];


export default users;